### ISSUE TITLE
Increase interactivity!

### ISSUE THREAD

**Issue by nitinprakash96** [nitinprakash96/quotegen#5]
Add image quotes as a separate option for the user.!

**Comment by Rcsuax** [comment]
@nitinprakash96 Hey I am interested in taking this. Could you explain further on what you want done here :)

**Comment by nitinprakash96** [comment]
It's just a simple app that displays Text quotes but in a presentable way. I'm thinking of adding quotes that reside in an image file. Because some people may want to use image quotes instead of text quotes.

**Comment by Rcsuax** [comment]
@nitinprakash96 Haven't managed to find a free api solution for this. I could potentially use an [image api](https://pixabay.com/api/docs/) and then add a quote to the image for display.

**Comment by nitinprakash96** [comment]
This should work fine @Rcsuax

**Comment by Rcsuax** [comment]
@nitinprakash96 i have created a pull request for this.
I added some base functionality to call image quotes and open them in a new tab.

**Comment by nitinprakash96** [comment]
@Rcsuax Image quote won't work.

**Comment by Rcsuax** [comment]
@nitinprakash96 [Works on codepen](http://codepen.io/anon/pen/EgwpGY?editors=1010#l) on firefox

**Comment by nitinprakash96** [comment]
oh yeah, it does! But as of now there are only 2 images right?

**Comment by Rcsuax** [comment]
You probably only see the first two since all the images are returned in order from the api, might need a randomizer function! Also i set a limit on the images in the ajax request with  this parameter `per_page=50` .you could probably play around with the [image api](https://pixabay.com/api/docs/) and see what best suits your needs. :)
